apiVersion: v1
kind: Service
metadata:
  name: {{ include "aviation.fullname" . }}-backend-internal
  namespace: {{ .Values.global.namespace }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health
  labels:
    {{- include "aviation.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "aviation.backend.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aviation.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aviation.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "aviation.backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
